### PR TITLE
www.php.net - down

### PR DESCRIPTION
**Pull request by fliespl**
Download without www. prefix

### CODE REVIEW

**Comment by fliespl** [comment]
Also downloads.php.net has expired cert - maybe it should be switched to alternative source?

**Comment by fpoirotte** [comment]
Thank you for taking the time to issue this pull request.
However, this issue does not seem to occur when running the development branch of phpfarm (develop).

I'll issue a new release soon based on the development branch, so this issue should soon be fixed in the master branch too.

In the meantime, I'll keep this PR open as a reminder.

**Comment by jcisio** [comment]
Didn't see that. Opened https://github.com/fpoirotte/phpfarm/pull/18 to fix all.

**Comment by fpoirotte** [comment]
Version 0.3.0 was released a month ago. It includes the fix for this issue.

**Comment by fliespl** [comment]
In my case it didn't solve the issue - in rare cases www.php.net was still used in 0.3.0 (and it's broken)

NVM - I had wrong branch.

**Pull request closed without merging**
